name: SonarCloud

on:
  pull_request_target:
    types: [ labeled ]

jobs:

  sonarcloud:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'sonarcloud' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=brenoepics_at4j -P coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Summary Action
        uses: thecanadianroot/sonarcloud-summary-action@v1
        with:
          github-repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }} 
